parameters:
    public_directory: '%kernel.project_dir%/public/'
    frontend: '%env(APP_FRONTEND)%'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Security\Voter\GradeVoter:
        tags: [ 'security.voter' ]
    App\Event\Listener\Auth\LoginFailureListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginFailureEvent, method: onLoginFailure }
    App\Event\Listener\Grade\GradeAssignedListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\GradeAssignedEvent, method: onGradeAssigned }
    App\Support\Helper\FileHelper:
        arguments:
            $publicDir: '%public_directory%'
    admin.student:
        class: App\Admin\StudentAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Student, manager_type: orm, label: Student }
    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, manager_type: orm, label: User, show_in_dashboard: false }
    admin.subject:
        class: App\Admin\SubjectAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Subject, manager_type: orm, label: Subject }
    admin.teacher:
        class: App\Admin\TeacherAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Teacher, manager_type: orm, label: Teacher }
    admin.classroom:
        class: App\Admin\ClassroomAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Classroom, manager_type: orm, label: Classroom }
    admin.lessons:
        class: App\Admin\LessonAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Lesson, manager_type: orm, label: Lesson }